# Generated by Django 6.0.2 on 2026-03-03 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ProfessorID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.CharField(max_length=20, unique=True)),
                ('CourseName', models.CharField(max_length=100)),
                ('Credits', models.IntegerField()),
                ('Amount_per_Credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermBolea.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermBolea.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermBolea.professor')),
            ],
        ),
    ]
