# Generated by Django 5.2.11 on 2026-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_age', models.IntegerField(max_length=10)),
                ('applicant_contact', models.IntegerField(max_length=12)),
                ('applicant_email', models.CharField(max_length=200)),
            ],
        ),
    ]
